// colors will be defined here along with spacing variables and so on
// will have index.css export containing variables for colors and spacings
//
// also will export js file with colors
// colors will be generated by js files and injected during webpack build
// spacings will be defined explicitly with css file
