// colors will be defined here along with spacing variables and so on
// will have index.css export containing variables for colors and spacings
//
// also will export js file with colors
// colors will be generated by js files and injected during build
// spacings will be defined explicitly with css file

const Values = require("values.js");
const gray = "#bdc3c7";
const white = "#ffffff";
const grayColor = new Values(gray);

const grayTints = grayColor.tints(7);
const grayShades = grayColor.shades(7);

const mapColors = items =>
  items.reduce(
    (acc, item, i) =>
      Object.assign({}, acc, {
        [i + 1 + "0"]: `#${item.hex}`
      }),
    {}
  );

export const colors = {
  white,
  gray,
  "gray-tint": mapColors(grayTints),
  "gray-shade": mapColors(grayShades)
};
